### ISSUE TITLE
i茅台脚本商品ID不知道怎么对应产品

### ISSUE THREAD

**Issue by Catnipll** [FoKit/Scripts#10]
大佬您好，您的i茅台脚本里【* 环境变量：export MT_ITEM_BLACK="2478|10056"  // 申购商品ID黑名单，多个ID以 | 隔开，留空为随机申购所有商品】这一条，没有找到详细的对应关系，不知道哪个ID对应哪个产品，如果大佬方便的话，想麻烦大佬可以告知一下如何获取相应产品ID吗，要不然无法精准屏蔽不想申购的产品，谢谢大佬！
![IMG_3697](https://github.com/FoKit/Scripts/assets/64342866/abd5c858-067b-4580-bd01-b080fbd21902)
![IMG_3698](https://github.com/FoKit/Scripts/assets/64342866/28f19398-8cc2-4cff-9dc2-8aab23a9b107)

**Comment by FoKit** [comment]
10213 - 贵州茅台酒（癸卯兔年）
10214 - 贵州茅台酒（癸卯兔年）x2
2478 - 贵州茅台酒（珍品）
10056 - 53%vol 500ml 茅台1935

**Comment by Catnipll** [comment]
> 10213 - 贵州茅台酒（癸卯兔年） 10214 - 贵州茅台酒（癸卯兔年）x2 2478 - 贵州茅台酒（珍品） 10056 - 53%vol 500ml 茅台1935

谢谢大佬，麻烦您了，感谢

**Comment by zzc-lxy** [comment]
> 10213 - 贵州茅台酒（癸卯兔年） 10214 - 贵州茅台酒（癸卯兔年）x2 2478 - 贵州茅台酒（珍品） 10056 - 53%vol 500ml 茅台1935

你好 为什么boxjs订阅以后更改的i茅台里的应用设置总会失效 会用之前特定的某次设置内容来代替
