### ISSUE TITLE
建行生活使用nodejs的参数问题

### ISSUE THREAD

**Issue by sakurawill** [FoKit/Scripts#14]
请问下使用nodejs跑的话，需要用到的参数有样例吗？
例如JHSH_BODY、JHSH_LOGIN_INFO的示例样式，要填入哪些内容才可以正常跑呢？

**Comment by FoKit** [comment]
export JHSH_BODY='{"ACT_ID":"","MEB_ID":"","USR_TEL":"","REGION_CODE":"","chnlType":"","regionCode":"","MID":""}'

export JHSH_LOGIN_INFO='{"DeviceId":"","MBCUserAgent":"","Body":""}'

建议通过手机代理工具获取所需数据，再从 boxjs 提取对应变量数据到 node.js 执行。

**Comment by sakurawill** [comment]
完美解决，谢谢。

**Comment by zadishu** [comment]
"MID":""}'  实在找不出来是哪个

**Comment by zadishu** [comment]
> export JHSH_BODY='{"ACT_ID":"","MEB_ID":"","USR_TEL":"","REGION_CODE":"","chnlType":"","regionCode":"","MID":""}'
> 
> export JHSH_LOGIN_INFO='{"DeviceId":"","MBCUserAgent":"","Body":""}'
> 
> 建议通过手机代理工具获取所需数据，再从 boxjs 提取对应变量数据到 node.js 执行。


"MID":""}' 实在找不出来是哪个
