### ISSUE TITLE
大佬 现在还能用吗   签到可以、领取失败了

### ISSUE THREAD

**Issue by shishixiu** [FoKit/Scripts#16]
尝试领取[外卖]券
Response code 487 (Unknown)
{"errMsg":"mebId must not be empty!","newErrMsg":"未能处理您的请求。如有疑问，请咨询在线客服或致电95533","data":{},"reqFlowNo":"1051003261699229904350840","errCode":"YBLA3341C821"}

**Comment by FoKit** [comment]
经过测试可正常领取优惠券
