### ISSUE TITLE
Hisense.js 打地鼠消耗积分兑换次数功能未执行

### ISSUE THREAD

**Issue by Bogaerde** [FoKit/Scripts#18]
1. 版本

- iPadOS 16.6.1
- Quantumult X 1.4.1-813
- Hisense.js 2023-11-16 更新

2. 推测原因

- **HISENSE_PARTY_EXCHANGE** 始终为 false 导致 125-134 行未执行

3. 建议

- 抓包并分析
`let HISENSE_PARTY_EXCHANGE = ($.isNode() ? process.env.HISENSE_PARTY_EXCHANGE : $.getdata(HISENSE_PARTY_EXCHANGE_KEY)) || 'false'; `

**Comment by FoKit** [comment]
你好，脚本默认不使用积分兑换游戏机会，如有需要可自行设置代理缓存（BoxJs）数据键“ HISENSE_PARTY_EXCHANGE” 为 "true"，感谢你的反馈。

**Comment by Bogaerde** [comment]
感谢，不过貌似Boxjs订阅里只有三个内置数据，未包含HISENSE_PARTY_EXCHANGE

**Comment by FoKit** [comment]
可通过 [数据查看器](http://boxjs.com/#/viewer) 进行配置

**Comment by Bogaerde** [comment]
感谢已解决！
