### ISSUE TITLE
建行生活显示“建行生活应用不支持设备使用代理访问”

### ISSUE THREAD

**Issue by MyLovePoppet** [FoKit/Scripts#2]
如标题，我使用一些跳过代理检测的规则后进行签到，例如https://github.com/scomper/Surge/blob/1d69e8071122a885c98900e0c43512fdab27b6c4/Modules/Skip%20Proxy%20List.sgmodule#L2，貌似没有获取到建行生活的cookie

**Comment by FoKit** [comment]
![photo_2023-08-01_10-02-53](https://github.com/FoKit/Scripts/assets/44187836/e4b2fb21-5f18-403b-8470-f1df0ffb9445)

经过测试，使用这个模块跳过代理检测可以正常获取签到数据
https://raw.githubusercontent.com/mieqq/mieqq/master/skip-proxy-lists.sgmodule

获取建行生活签到数据
https://raw.githubusercontent.com/FoKit/Scripts/main/rewrite/get_jhsh_cookie.sgmodule

**Comment by double1025** [comment]
请问安卓如何使用模块？

**Comment by JONREAN2** [comment]
请问ck格式是啥

**Comment by NowhereintheDeepCloud** [comment]
请问shadowrocket有没有能屏蔽建行生活代理检测的规则之类的
