### ISSUE TITLE
建行生活 stash 无法保存 cookie

### ISSUE THREAD

**Issue by vzyw** [FoKit/Scripts#20]
安装后访问建行签到页一次，提示数据获取成功。定时执行的时候，又会显示请先获取 cookie
![IMG_3012](https://github.com/FoKit/Scripts/assets/13702483/e82c42d7-8fff-4658-95be-e851b2c194b3)

**Comment by vzyw** [comment]
我尝试了在这两个位置增加 stash 的判断，还是不能持久化
<img width="666" alt="image" src="https://github.com/FoKit/Scripts/assets/13702483/02da67ed-6478-4513-bdfc-87e6d37ce25f">

**Comment by FoKit** [comment]
抱歉，未用过 Stash App 暂时无法处理这个问题。

**Comment by YuriKing998** [comment]
大佬，能不能增加一个imaotai自动抢100毫升小茅台的脚本啊

**Comment by FoKit** [comment]
> 安装后访问建行签到页一次，提示数据获取成功。定时执行的时候，又会显示请先获取 cookie
> ![IMG_3012](https://private-user-images.githubusercontent.com/13702483/284504032-e82c42d7-8fff-4658-95be-e851b2c194b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2Mjg1NjAsIm5iZiI6MTcwNjYyODI2MCwicGF0aCI6Ii8xMzcwMjQ4My8yODQ1MDQwMzItZTgyYzQyZDctOGZmZi00NjU4LTk1YmUtZTg1MWIyYzE5NGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE1MjQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNmJiYjZjNGE2YTg1ZjFlOWFkOWFkYjZlMWZhMzNmNmZmYzUwNjM4NWUyMzgzY2I5YTUzZDA1MDAwYmQ0NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sn6JYzLMz9cSvgbuwRoZzMor75m8qF1qrnwqzawuU8Y)

已修复，请使用 Stash 更新脚本后重试。
