### ISSUE TITLE
建行生活

### ISSUE THREAD

**Issue by shuffleer** [FoKit/Scripts#21]
===== 账号[132]开始签到 =====

TypeError: Cannot read properties of undefined (reading 'body')  

JHSH_LOGIN_INFO中的body是否是JHSH_BODY的值？填上报错这个

**Comment by FoKit** [comment]
JHSH_LOGIN_INFO 中的 body 为 autoLogin 接口的请求 body，具体可查看 [代码](https://github.com/FoKit/Scripts/blob/main/scripts/jhsh_checkIn.js#L186)
