### ISSUE TITLE
捷停车改版了，好像用不了了

### ISSUE THREAD

**Issue by sakurawill** [FoKit/Scripts#22]
请问可以更新下嘛

**Comment by Jone2008** [comment]
把脚本115行的URL改成：https://jparking.jslife.com.cn/jparking-other-service/coupons/getSerialSign

**Comment by sakurawill** [comment]
> 把脚本115行的URL改成：https://jparking.jslife.com.cn/jparking-other-service/coupons/getSerialSign

这样是不行的，签到不在这个url里进行了

**Comment by FoKit** [comment]
正在修复，晚点更新

**Comment by FoKit** [comment]
脚本已更新，请更新脚本后重试

**Comment by Jone2008** [comment]
> > 把脚本115行的URL改成：https://jparking.jslife.com.cn/jparking-other-service/coupons/getSerialSign
> 
> 这样是不行的，签到不在这个url里进行了

是可以的，我自己抓包并且运行成功才回复你的。不过大佬已经修复好了。点赞

**Comment by Jone2008** [comment]
> 脚本已更新，请更新脚本后重试

完美运行，谢谢大佬修复。
不过有一个问题，就是抓包的成功后如果不退出，会重复抓取相同账号并@隔开为第二账号，运行的时候也会运行多多账号，运行结果提示第二账号重复签到。

**Comment by FoKit** [comment]
> > 脚本已更新，请更新脚本后重试
> 
> 完美运行，谢谢大佬修复。 不过有一个问题，就是抓包的成功后如果不退出，会重复抓取相同账号并@隔开为第二账号，运行的时候也会运行多多账号，运行结果提示第二账号重复签到。

已修复重复抓取相同账号分隔为多账号问题，请更新脚本后重试，感谢你的反馈。

**Comment by Jone2008** [comment]
> > > 脚本已更新，请更新脚本后重试
> > 
> > 
> > 完美运行，谢谢大佬修复。 不过有一个问题，就是抓包的成功后如果不退出，会重复抓取相同账号并@隔开为第二账号，运行的时候也会运行多多账号，运行结果提示第二账号重复签到。
> 
> 已修复重复抓取相同账号分隔为多账号问题，请更新脚本后重试，感谢你的反馈。

感谢修复，现已正常
