### ISSUE TITLE
请问下PP停车CODESERVER_ADDRESS、CODESERVER_FUN怎么获取呢

### ISSUE THREAD

**Issue by sakurawill** [FoKit/Scripts#26]
请问下PP停车CODESERVER_ADDRESS、CODESERVER_FUN怎么获取呢

**Comment by FoKit** [comment]
配置 PP_TOKEN 变量即可

**Comment by sakurawill** [comment]
PP_TOKEN有什么格式吗？我配置了好像提示我还是没有token

**Comment by sakurawill** [comment]
提示
⚠️ 未配置微信 Code Server。

❗️PP 停车, 错误!
Error: 未找到 Token 变量 ❌
    at main (/ql/data/scripts/FoKit_Scripts/pp_parking.js:112:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /ql/data/scripts/FoKit_Scripts/pp_parking.js:341:5

**Comment by FoKit** [comment]
Token 以数组形式保存，["eyJhbGciOi…"]  不含 Bearer
