### ISSUE TITLE
建行生活断签应如何配置

### ISSUE THREAD

**Issue by JUNZHOU8** [FoKit/Scripts#28]
您好，请问建行生活的断签变量"JHSH_SKIPDAY"，应当如何配置才能实现每签到3天，第四天断签呢？
SKIPDAY变量我填入数字4时，希望它周四断签，第一周正常，第二周周一会正常签到。

**Comment by FoKit** [comment]
你好，请问你是在 Node.js（青龙）环境下执行的吗？

**Comment by JUNZHOU8** [comment]
您好，是的。

**Comment by FoKit** [comment]
请在脚本同目录内创建内容为 {"JHSH_SKIPDAY": "3"} 的 box.dat 文件并更新脚本后重试，同时需要从环境变量中删除 JHSH_SKIPDAY 变量。

**Comment by JUNZHOU8** [comment]
好的，已经按照说明配置，感谢。
