### ISSUE TITLE
loon无法抓取建行生活ck

### ISSUE THREAD

**Issue by Jessire** [FoKit/Scripts#3]
手动签到loon无任何提示

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by FoKit** [comment]
[MITM]
hostname = yunbusiness.ccb.com

[Script]
http-request ^https:\/\/yunbusiness\.ccb\.com\/clp_coupon\/txCtrl\?txcode=A3341A040 tag=建行生活, script-path=https://raw.githubusercontent.com/FoKit/Scripts/main/scripts/jhsh_checkIn.js,requires-body=1

cron "17 7 * * *" script-path=https://raw.githubusercontent.com/FoKit/Scripts/main/scripts/jhsh_checkIn.js,tag = 建行生活,enable=true

试试上面这个，或者使用下面的模块转换一下
https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/modules/script-hub.loon.plugin

**Comment by Jone2008** [comment]
抓包搜索请求体 ACT_ID 把内容填进去，加上电话号码参数"USR_TEL"就可以运行了。我搜的是 txcode=A3341A038

**Comment by JONREAN2** [comment]
> 抓包搜索请求体 ACT_ID 把内容填进去，加上电话号码参数"USR_TEL"就可以运行了。我搜的是 txcode=A3341A038

USR_TEL 加哪里啊

**Comment by FoKit** [comment]
{"ACT_ID":"20230628070000000001","MEB_ID":"YSM202301777777777","USR_TEL":"18888888888","REGION_CODE":"440100","chnlType":"1","regionCode":"440100","MID":"159"}
