### ISSUE TITLE
建行生活失效了

### ISSUE THREAD

**Issue by LisonFan** [FoKit/Scripts#33]
![IMG_DB1A96898984-1](https://github.com/FoKit/Scripts/assets/9424775/07c45767-cdd3-4ee1-bc9e-eef4b2c5f089)
![IMG_9EAF28764ED8-1](https://github.com/FoKit/Scripts/assets/9424775/38202da5-6c50-4c9c-8124-075584ca8d76)

**Comment by FoKit** [comment]
请重新获取数据
