### ISSUE TITLE
如何更改 i 茅台 门店地址？

### ISSUE THREAD

**Issue by WillpowerJin** [FoKit/Scripts#9]
大佬好，请问如何把脚本中的地址更改为“北京”？

let MT_PROVINCE = $.getdata('MT_PROVINCE') || '北京市';
let MT_CITY = $.getdata('MT_CITY') || '北京市';
let MT_DISTRICT = $.getdata('MT_DISTRICT') || '';

这样修改是否正确？脚本在圈X运行后会出现“仁怀市”相应信息，是否为正常情况？

望大佬回复，万分感谢！

**Comment by FoKit** [comment]
1. 添加 BoxJs 订阅：https://raw.githubusercontent.com/FoKit/Scripts/main/boxjs/fokit.boxjs.json
2. 在 BoxJs 内配置需要申购的省份和城市。

[BoxJs 使用教程：](https://docs.boxjs.app/)

![photo_2023-10-10_18-12-52](https://github.com/FoKit/Scripts/assets/44187836/dbb74bfb-9d95-4010-870a-14edd09c0fea)
